import { prisma } from '@/lib/db'
import { IncidentStatus, IncidentSeverity } from '@prisma/client'

interface CheckResult {
  checkId: string
  serviceId: string
  serviceName: string
  success: boolean
  timestamp: Date
  error?: string
  responseTime?: number
}

interface ServiceWithSettings {
  id: string
  name: string
  autoIncidentEnabled: boolean
  autoIncidentThreshold: number
  autoIncidentCooldown: number
  lastAutoIncident?: Date | null
}

export class AutoIncidentManager {
  private static instance: AutoIncidentManager
  private consecutiveFailures = new Map<string, number>()
  private lastCheckedAt = new Map<string, Date>()

  static getInstance(): AutoIncidentManager {
    if (!AutoIncidentManager.instance) {
      AutoIncidentManager.instance = new AutoIncidentManager()
    }
    return AutoIncidentManager.instance
  }

  /**
   * Handle a check result and potentially create/update incidents
   */
  async handleCheckResult(result: CheckResult): Promise<void> {
    try {
      const service = await this.getServiceSettings(result.serviceId)

      if (!service) {
        console.warn(`[AUTO-INCIDENT] Service ${result.serviceId} not found`)
        return
      }

      if (!service.autoIncidentEnabled) {
        console.log(`[AUTO-INCIDENT] Auto-incidents disabled for ${service.name}`)
        return
      }

      await this.processCheckResult(service, result)
    } catch (error) {
      console.error('[AUTO-INCIDENT] Error handling check result:', error)
    }
  }

  private async getServiceSettings(serviceId: string): Promise<ServiceWithSettings | null> {
    const service = await prisma.service.findUnique({
      where: { id: serviceId },
      select: {
        id: true,
        name: true,
        autoIncidentEnabled: true,
        autoIncidentThreshold: true,
        autoIncidentCooldown: true,
        lastAutoIncident: true
      }
    })

    return service
  }

  private async processCheckResult(service: ServiceWithSettings, result: CheckResult): Promise<void> {
    const serviceKey = service.id
    const currentFailures = this.consecutiveFailures.get(serviceKey) || 0

    if (!result.success) {
      // Service is down - increment failure counter
      const newFailureCount = currentFailures + 1
      this.consecutiveFailures.set(serviceKey, newFailureCount)
      this.lastCheckedAt.set(serviceKey, result.timestamp)

      console.log(`[AUTO-INCIDENT] ${service.name} failed check ${newFailureCount}/${service.autoIncidentThreshold}`)

      // Check if we should create an incident
      if (newFailureCount >= service.autoIncidentThreshold) {
        await this.handleServiceDown(service, result, newFailureCount)
      }
    } else {
      // Service is back up
      if (currentFailures > 0) {
        console.log(`[AUTO-INCIDENT] ${service.name} is back online after ${currentFailures} failures`)
        await this.handleServiceRecovery(service, result)
      }

      // Reset failure counter
      this.consecutiveFailures.set(serviceKey, 0)
      this.lastCheckedAt.set(serviceKey, result.timestamp)
    }
  }

  private async handleServiceDown(
    service: ServiceWithSettings,
    result: CheckResult,
    failureCount: number
  ): Promise<void> {
    // Check cooldown period
    if (service.lastAutoIncident) {
      const timeSinceLastIncident = result.timestamp.getTime() - service.lastAutoIncident.getTime()
      const cooldownMs = service.autoIncidentCooldown * 1000

      if (timeSinceLastIncident < cooldownMs) {
        console.log(`[AUTO-INCIDENT] ${service.name} in cooldown period (${Math.round(timeSinceLastIncident / 1000)}s / ${service.autoIncidentCooldown}s)`)
        return
      }
    }

    // Check if there's already an active auto-incident
    const activeIncident = await prisma.incident.findFirst({
      where: {
        serviceId: service.id,
        isAutoGenerated: true,
        status: {
          in: [IncidentStatus.INVESTIGATING, IncidentStatus.MONITORING]
        }
      }
    })

    if (activeIncident) {
      console.log(`[AUTO-INCIDENT] Active auto-incident already exists for ${service.name}`)
      return
    }

    // Create new auto-incident
    await this.createAutoIncident(service, result, failureCount)
  }

  private async createAutoIncident(
    service: ServiceWithSettings,
    result: CheckResult,
    failureCount: number
  ): Promise<void> {
    try {
      const title = `${service.name} is experiencing issues`
      const description = `Automated incident: Service has failed ${failureCount} consecutive health checks. We are investigating the issue.`

      // Determine severity based on failure count
      let severity: IncidentSeverity = IncidentSeverity.MEDIUM
      if (failureCount >= 5) {
        severity = IncidentSeverity.HIGH
      } else if (failureCount >= 10) {
        severity = IncidentSeverity.CRITICAL
      }

      // Generate slug
      const slug = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '') +
        '-' + Date.now()

      // Ensure system user exists
      await this.ensureSystemUser()

      // Create incident
      const incident = await prisma.incident.create({
        data: {
          title,
          slug,
          description,
          severity,
          status: IncidentStatus.INVESTIGATING,
          serviceId: service.id,
          isAutoGenerated: true,
          autoStatus: 'investigating',
          createdBy: 'system',
          startTime: result.timestamp,
          tags: ['auto-generated', 'outage']
        }
      })

      // Create initial update
      await prisma.incidentUpdate.create({
        data: {
          incidentId: incident.id,
          title: 'Incident Detected',
          message: `We are investigating reports of issues with ${service.name}. ` +
                  `The service has failed ${failureCount} consecutive health checks. ` +
                  `Our team has been automatically notified and is looking into this.`,
          status: IncidentStatus.INVESTIGATING,
          authorName: 'YorkHost Monitoring',
          isStatusChange: true
        }
      })

      // Update service's last auto-incident timestamp
      await prisma.service.update({
        where: { id: service.id },
        data: { lastAutoIncident: result.timestamp }
      })

      console.log(`[AUTO-INCIDENT] ✅ Created auto-incident ${incident.id} for ${service.name}`)
    } catch (error) {
      console.error(`[AUTO-INCIDENT] Failed to create incident for ${service.name}:`, error)
    }
  }

  private async handleServiceRecovery(
    service: ServiceWithSettings,
    result: CheckResult
  ): Promise<void> {
    // Find active auto-incident
    const activeIncident = await prisma.incident.findFirst({
      where: {
        serviceId: service.id,
        isAutoGenerated: true,
        manualTakeover: false, // Don't auto-resolve if admin took control
        status: {
          in: [IncidentStatus.INVESTIGATING, IncidentStatus.MONITORING]
        }
      }
    })

    if (!activeIncident) {
      return
    }

    // Transition to monitoring status first
    if (activeIncident.status === IncidentStatus.INVESTIGATING) {
      await this.transitionToMonitoring(activeIncident, service, result)
    } else if (activeIncident.status === IncidentStatus.MONITORING) {
      // Service has been stable, resolve the incident
      await this.resolveIncident(activeIncident, service, result)
    }
  }

  private async transitionToMonitoring(
    incident: any,
    service: ServiceWithSettings,
    result: CheckResult
  ): Promise<void> {
    try {
      await prisma.incident.update({
        where: { id: incident.id },
        data: {
          status: IncidentStatus.MONITORING,
          autoStatus: 'monitoring'
        }
      })

      await prisma.incidentUpdate.create({
        data: {
          incidentId: incident.id,
          title: 'Service Restored - Monitoring',
          message: `${service.name} appears to be responding normally again. ` +
                  `We are monitoring the service closely to ensure stability before marking this incident as resolved.`,
          status: IncidentStatus.MONITORING,
          authorName: 'YorkHost Monitoring',
          isStatusChange: true
        }
      })

      console.log(`[AUTO-INCIDENT] 📊 Transitioned incident ${incident.id} to monitoring for ${service.name}`)
    } catch (error) {
      console.error(`[AUTO-INCIDENT] Failed to transition to monitoring:`, error)
    }
  }

  private async resolveIncident(
    incident: any,
    service: ServiceWithSettings,
    result: CheckResult
  ): Promise<void> {
    try {
      const downtime = result.timestamp.getTime() - incident.startTime.getTime()
      const downtimeMinutes = Math.floor(downtime / 60000)
      const downtimeHours = Math.floor(downtimeMinutes / 60)
      const downtimeText = downtimeHours > 0
        ? `${downtimeHours}h ${downtimeMinutes % 60}m`
        : `${downtimeMinutes}m`

      await prisma.incident.update({
        where: { id: incident.id },
        data: {
          status: IncidentStatus.RESOLVED,
          endTime: result.timestamp,
          resolvedAt: result.timestamp,
          autoStatus: 'resolved'
        }
      })

      await prisma.incidentUpdate.create({
        data: {
          incidentId: incident.id,
          title: 'Incident Resolved',
          message: `This incident has been resolved. ` +
                  `${service.name} is now operating normally. ` +
                  `Total downtime was approximately ${downtimeText}. ` +
                  `We apologize for any inconvenience caused.`,
          status: IncidentStatus.RESOLVED,
          authorName: 'YorkHost Monitoring',
          isStatusChange: true
        }
      })

      console.log(`[AUTO-INCIDENT] ✅ Resolved incident ${incident.id} for ${service.name} (downtime: ${downtimeText})`)
    } catch (error) {
      console.error(`[AUTO-INCIDENT] Failed to resolve incident:`, error)
    }
  }

  /**
   * Allow admin to take manual control of an auto-incident
   */
  async takeManualControl(incidentId: string, adminUserId: string): Promise<boolean> {
    try {
      const incident = await prisma.incident.findUnique({
        where: { id: incidentId },
        select: { id: true, isAutoGenerated: true, manualTakeover: true }
      })

      if (!incident || !incident.isAutoGenerated || incident.manualTakeover) {
        return false
      }

      await prisma.incident.update({
        where: { id: incidentId },
        data: {
          manualTakeover: true,
          createdBy: adminUserId // Transfer ownership to admin
        }
      })

      await prisma.incidentUpdate.create({
        data: {
          incidentId,
          title: 'Manual Control Taken',
          message: 'An administrator has taken manual control of this incident. Automatic updates have been disabled.',
          authorName: 'Administrator',
          isStatusChange: false
        }
      })

      console.log(`[AUTO-INCIDENT] 👤 Admin ${adminUserId} took control of incident ${incidentId}`)
      return true
    } catch (error) {
      console.error('[AUTO-INCIDENT] Failed to take manual control:', error)
      return false
    }
  }

  /**
   * Ensure system user exists for auto-incidents
   */
  private async ensureSystemUser(): Promise<void> {
    try {
      const existingUser = await prisma.user.findUnique({
        where: { id: 'system' }
      })

      if (!existingUser) {
        await prisma.user.create({
          data: {
            id: 'system',
            discordId: 'system',
            username: 'system',
            email: 'system@yorkhost.fr',
            avatar: null
          }
        })
        console.log('[AUTO-INCIDENT] ✅ Created system user')
      }
    } catch (error) {
      console.error('[AUTO-INCIDENT] Failed to ensure system user:', error)
    }
  }

  /**
   * Get statistics about auto-incidents
   */
  async getAutoIncidentStats(serviceId?: string): Promise<any> {
    const where = serviceId ? { serviceId, isAutoGenerated: true } : { isAutoGenerated: true }

    const stats = await prisma.incident.groupBy({
      by: ['status'],
      where,
      _count: { id: true }
    })

    const total = await prisma.incident.count({ where })

    const resolved = await prisma.incident.count({
      where: { ...where, status: IncidentStatus.RESOLVED }
    })

    const avgResolutionTime = await prisma.incident.aggregate({
      where: {
        ...where,
        status: IncidentStatus.RESOLVED,
        endTime: { not: null }
      },
      _avg: {
        // Calculate average resolution time in minutes
      }
    })

    return {
      total,
      resolved,
      byStatus: stats.reduce((acc, stat) => {
        acc[stat.status] = stat._count.id
        return acc
      }, {} as Record<string, number>),
      resolutionRate: total > 0 ? (resolved / total) * 100 : 0
    }
  }
}

// Export singleton instance
export const autoIncidentManager = AutoIncidentManager.getInstance()