import { NextRequest, NextResponse } from 'next/server'
import { requireAuth } from '@/lib/auth/jwt'
import { prisma } from '@/lib/db'
import { autoIncidentManager } from '@/lib/auto-incident-manager'
import { z } from 'zod'

const updateAutoIncidentSchema = z.object({
  serviceId: z.string().cuid(),
  autoIncidentEnabled: z.boolean(),
  autoIncidentThreshold: z.number().min(1).max(10).optional(),
  autoIncidentCooldown: z.number().min(60).max(3600).optional() // 1 minute to 1 hour
})

const takeControlSchema = z.object({
  incidentId: z.string().cuid()
})

export async function GET(request: NextRequest) {
  try {
    const auth = await requireAuth(request)

    if (!auth.authorized) {
      return NextResponse.json({
        success: false,
        error: auth.error || 'Unauthorized'
      }, { status: 401 })
    }

    const { searchParams } = new URL(request.url)
    const serviceId = searchParams.get('serviceId')

    // Get auto-incident stats
    const stats = await autoIncidentManager.getAutoIncidentStats(serviceId || undefined)

    // Get services with their auto-incident settings
    const services = await prisma.service.findMany({
      where: serviceId ? { id: serviceId } : {},
      select: {
        id: true,
        name: true,
        autoIncidentEnabled: true,
        autoIncidentThreshold: true,
        autoIncidentCooldown: true,
        lastAutoIncident: true,
        incidents: {
          where: { isAutoGenerated: true },
          select: {
            id: true,
            title: true,
            status: true,
            isAutoGenerated: true,
            manualTakeover: true,
            startTime: true,
            endTime: true
          },
          orderBy: { startTime: 'desc' },
          take: 5
        }
      },
      orderBy: { name: 'asc' }
    })

    return NextResponse.json({
      success: true,
      data: {
        stats,
        services
      }
    })
  } catch (error) {
    console.error('Auto-incidents API error:', error)

    return NextResponse.json({
      success: false,
      error: 'Failed to fetch auto-incident data'
    }, { status: 500 })
  }
}

export async function PUT(request: NextRequest) {
  try {
    const auth = await requireAuth(request)

    if (!auth.authorized) {
      return NextResponse.json({
        success: false,
        error: auth.error || 'Unauthorized'
      }, { status: 401 })
    }

    const body = await request.json()
    const data = updateAutoIncidentSchema.parse(body)

    // Update service auto-incident settings
    const updatedService = await prisma.service.update({
      where: { id: data.serviceId },
      data: {
        autoIncidentEnabled: data.autoIncidentEnabled,
        ...(data.autoIncidentThreshold && { autoIncidentThreshold: data.autoIncidentThreshold }),
        ...(data.autoIncidentCooldown && { autoIncidentCooldown: data.autoIncidentCooldown })
      },
      select: {
        id: true,
        name: true,
        autoIncidentEnabled: true,
        autoIncidentThreshold: true,
        autoIncidentCooldown: true
      }
    })

    // Create audit log
    await prisma.auditLog.create({
      data: {
        userId: auth.user!.userId,
        action: 'UPDATE',
        resource: 'AUTO_INCIDENT_SETTINGS',
        resourceId: data.serviceId,
        details: {
          serviceName: updatedService.name,
          changes: data
        }
      }
    })

    return NextResponse.json({
      success: true,
      data: updatedService
    })
  } catch (error) {
    console.error('Update auto-incident settings error:', error)

    if (error instanceof z.ZodError) {
      return NextResponse.json({
        success: false,
        error: 'Invalid input data',
        details: error.errors
      }, { status: 400 })
    }

    return NextResponse.json({
      success: false,
      error: 'Failed to update auto-incident settings'
    }, { status: 500 })
  }
}

export async function POST(request: NextRequest) {
  try {
    const auth = await requireAuth(request)

    if (!auth.authorized) {
      return NextResponse.json({
        success: false,
        error: auth.error || 'Unauthorized'
      }, { status: 401 })
    }

    const body = await request.json()
    const { action, ...data } = body

    if (action === 'take-control') {
      const { incidentId } = takeControlSchema.parse(data)

      const success = await autoIncidentManager.takeManualControl(
        incidentId,
        auth.user!.userId
      )

      if (!success) {
        return NextResponse.json({
          success: false,
          error: 'Failed to take control - incident may not be auto-generated or already under manual control'
        }, { status: 400 })
      }

      // Create audit log
      await prisma.auditLog.create({
        data: {
          userId: auth.user!.userId,
          action: 'TAKE_CONTROL',
          resource: 'AUTO_INCIDENT',
          resourceId: incidentId,
          details: {
            action: 'manual_takeover'
          }
        }
      })

      return NextResponse.json({
        success: true,
        message: 'Manual control taken successfully'
      })
    }

    return NextResponse.json({
      success: false,
      error: 'Unknown action'
    }, { status: 400 })
  } catch (error) {
    console.error('Auto-incident action error:', error)

    if (error instanceof z.ZodError) {
      return NextResponse.json({
        success: false,
        error: 'Invalid input data',
        details: error.errors
      }, { status: 400 })
    }

    return NextResponse.json({
      success: false,
      error: 'Failed to perform action'
    }, { status: 500 })
  }
}