'use client'

import { useState, useEffect } from 'react'
import AdminLayout from '@/components/admin/AdminLayout'
import {
  Settings,
  Zap,
  Clock,
  Shield,
  BarChart3,
  CheckCircle,
  XCircle,
  AlertTriangle,
  User,
  RefreshCw,
  Save,
  Eye,
  UserCheck,
  ChevronUp,
  ChevronDown
} from 'lucide-react'
import { motion, AnimatePresence } from 'framer-motion'
import { clsx } from 'clsx'

interface Service {
  id: string
  name: string
  autoIncidentEnabled: boolean
  autoIncidentThreshold: number
  autoIncidentCooldown: number
  lastAutoIncident?: string
  incidents: Incident[]
}

interface Incident {
  id: string
  title: string
  status: string
  isAutoGenerated: boolean
  manualTakeover: boolean
  startTime: string
  endTime?: string
}

interface Stats {
  total: number
  resolved: number
  byStatus: Record<string, number>
  resolutionRate: number
}

export default function AutoIncidentsPage() {
  const [services, setServices] = useState<Service[]>([])
  const [stats, setStats] = useState<Stats | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [saving, setSaving] = useState('')
  const [selectedServices, setSelectedServices] = useState<string[]>([])
  const [machines, setMachines] = useState<any[]>([])
  const [expandedGroups, setExpandedGroups] = useState<Set<string>>(new Set())

  useEffect(() => {
    fetchData()
    fetchMachinesAndServices()
  }, [])

  const fetchData = async () => {
    try {
      const response = await fetch('/api/admin/auto-incidents')
      if (!response.ok) throw new Error('Failed to fetch data')

      const result = await response.json()
      setServices(result.data.services)
      setStats(result.data.stats)
    } catch (err: any) {
      setError(err.message || 'Failed to load data')
    } finally {
      setLoading(false)
    }
  }

  const fetchMachinesAndServices = async () => {
    try {
      const response = await fetch('/api/admin/machines')
      const result = await response.json()
      if (result.success) {
        setMachines(result.data)
      }
    } catch (err: any) {
      console.error('Failed to fetch machines:', err)
    }
  }

  const toggleGroup = (groupId: string) => {
    const newExpanded = new Set(expandedGroups)
    if (newExpanded.has(groupId)) {
      newExpanded.delete(groupId)
    } else {
      newExpanded.add(groupId)
    }
    setExpandedGroups(newExpanded)
  }


  const toggleGroupSelection = (machine: any) => {
    const groupServiceIds = machine.services?.map((s: any) => s.id) || []
    const allSelected = groupServiceIds.every((id: string) => selectedServices.includes(id))

    if (allSelected) {
      setSelectedServices(selectedServices.filter(id => !groupServiceIds.includes(id)))
    } else {
      const newSelection = Array.from(new Set([...selectedServices, ...groupServiceIds]))
      setSelectedServices(newSelection)
    }
  }

  const toggleServiceSelection = (serviceId: string) => {
    if (selectedServices.includes(serviceId)) {
      setSelectedServices(selectedServices.filter(id => id !== serviceId))
    } else {
      setSelectedServices([...selectedServices, serviceId])
    }
  }

  const updateServiceSettings = async (serviceId: string, settings: Partial<Service>) => {
    setSaving(serviceId)
    try {
      const response = await fetch('/api/admin/auto-incidents', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          serviceId,
          ...settings
        })
      })

      if (!response.ok) throw new Error('Failed to update settings')

      // Update local state
      setServices(prev => prev.map(service =>
        service.id === serviceId
          ? { ...service, ...settings }
          : service
      ))
    } catch (err: any) {
      setError(err.message || 'Failed to update settings')
    } finally {
      setSaving('')
    }
  }

  const takeControl = async (incidentId: string) => {
    try {
      const response = await fetch('/api/admin/auto-incidents', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'take-control',
          incidentId
        })
      })

      if (!response.ok) throw new Error('Failed to take control')

      await fetchData() // Refresh data
    } catch (err: any) {
      setError(err.message || 'Failed to take control')
    }
  }

  const getStatusColor = (status: string) => {
    const colors: Record<string, string> = {
      INVESTIGATING: 'text-orange-600 bg-orange-50',
      MONITORING: 'text-blue-600 bg-blue-50',
      RESOLVED: 'text-green-600 bg-green-50'
    }
    return colors[status] || 'text-gray-600 bg-gray-50'
  }

  if (loading) {
    return (
      <AdminLayout>
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
        </div>
      </AdminLayout>
    )
  }

  return (
    <AdminLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold text-gray-900 dark:text-white">Auto-Incidents</h1>
            <p className="text-gray-500 dark:text-gray-400 mt-1">
              Manage automatic incident creation and monitoring
            </p>
          </div>
          <button
            onClick={fetchData}
            className="p-2 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg transition-colors"
            title="Refresh"
          >
            <RefreshCw size={20} />
          </button>
        </div>

        {/* Error Alert */}
        <AnimatePresence>
          {error && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              className="bg-red-50 text-red-700 p-4 rounded-lg flex items-start gap-3"
            >
              <div className="flex-1">
                <p className="font-medium">Error</p>
                <p className="text-sm mt-1">{error}</p>
              </div>
              <button onClick={() => setError('')} className="text-red-500 hover:text-red-700">
                ×
              </button>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Service Filter */}
        <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg shadow-sm border border-gray-200 dark:border-yorkhost-darkBorder">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-yorkhost-darkBorder">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center gap-2">
                <Settings size={20} />
                Service Filter
              </h3>
              <div className="flex items-center gap-3">
                <span className="text-sm text-gray-500 dark:text-gray-400">
                  {selectedServices.length} service(s) selected
                </span>
                {selectedServices.length > 0 && (
                  <button
                    onClick={() => setSelectedServices([])}
                    className="px-3 py-1 text-xs bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-600 dark:text-gray-300 rounded-full transition-colors"
                  >
                    Clear All
                  </button>
                )}
              </div>
            </div>
          </div>

          <div className="p-6">
            <div className="border border-gray-200 dark:border-gray-600 rounded-lg max-h-64 overflow-y-auto">
              {machines.map((machine) => (
                <div key={machine.id} className="border-b border-gray-200 dark:border-gray-700 last:border-b-0">
                  {/* Group Header */}
                  <div className="flex items-center justify-between p-3 hover:bg-gray-50 dark:hover:bg-gray-700">
                    <div className="flex items-center gap-3">
                      <button
                        type="button"
                        onClick={() => toggleGroup(machine.id)}
                        className="text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white"
                      >
                        {expandedGroups.has(machine.id) ? (
                          <ChevronUp className="w-4 h-4" />
                        ) : (
                          <ChevronDown className="w-4 h-4" />
                        )}
                      </button>
                      <div className="flex items-center gap-2">
                        <span className="font-medium text-gray-900 dark:text-white">{machine.name}</span>
                        <span className="text-sm text-gray-500">
                          ({machine.services.length} services)
                        </span>
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={() => toggleGroupSelection(machine)}
                      className={`px-3 py-1 text-xs rounded-full transition-colors ${
                        machine.services?.every((s: any) => selectedServices.includes(s.id))
                          ? 'bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300'
                          : 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-400'
                      }`}
                    >
                      {machine.services?.every((s: any) => selectedServices.includes(s.id))
                        ? 'Deselect All'
                        : 'Select All'}
                    </button>
                  </div>

                  {/* Services in Group */}
                  {expandedGroups.has(machine.id) && (
                    <div className="bg-gray-50 dark:bg-gray-800">
                      {machine.services.map((service: any) => (
                        <label
                          key={service.id}
                          className="flex items-center gap-3 p-3 pl-10 hover:bg-gray-100 dark:hover:bg-gray-700 cursor-pointer"
                        >
                          <input
                            type="checkbox"
                            checked={selectedServices.includes(service.id)}
                            onChange={() => toggleServiceSelection(service.id)}
                            className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                          />
                          <div className="flex-1">
                            <span className="text-sm font-medium text-gray-900 dark:text-white">{service.name}</span>
                            {service.description && (
                              <p className="text-xs text-gray-500 dark:text-gray-400">{service.description}</p>
                            )}
                          </div>
                          <div className="flex items-center gap-2">
                            <div className={clsx(
                              'w-2 h-2 rounded-full',
                              service.autoIncidentEnabled ? 'bg-green-500' : 'bg-gray-400'
                            )}></div>
                            <span className="text-xs text-gray-500">
                              {service.autoIncidentEnabled ? 'Auto' : 'Manual'}
                            </span>
                          </div>
                        </label>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Stats Cards */}
        {stats && (
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg p-6 border border-gray-200 dark:border-yorkhost-darkBorder">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-blue-100 dark:bg-blue-900/30 rounded-lg">
                  <BarChart3 size={20} className="text-blue-600 dark:text-blue-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.total}</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Total Auto-Incidents</p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg p-6 border border-gray-200 dark:border-yorkhost-darkBorder">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-green-100 dark:bg-green-900/30 rounded-lg">
                  <CheckCircle size={20} className="text-green-600 dark:text-green-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.resolved}</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Resolved</p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg p-6 border border-gray-200 dark:border-yorkhost-darkBorder">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-orange-100 dark:bg-orange-900/30 rounded-lg">
                  <AlertTriangle size={20} className="text-orange-600 dark:text-orange-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.byStatus.INVESTIGATING || 0}</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Investigating</p>
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg p-6 border border-gray-200 dark:border-yorkhost-darkBorder">
              <div className="flex items-center gap-3">
                <div className="p-2 bg-purple-100 dark:bg-purple-900/30 rounded-lg">
                  <Zap size={20} className="text-purple-600 dark:text-purple-400" />
                </div>
                <div>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">{stats.resolutionRate.toFixed(1)}%</p>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Resolution Rate</p>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Services List */}
        <div className="bg-white dark:bg-yorkhost-darkCard rounded-lg shadow-sm border border-gray-200 dark:border-yorkhost-darkBorder">
          <div className="px-6 py-4 border-b border-gray-200 dark:border-yorkhost-darkBorder">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white flex items-center gap-2">
                <Settings size={20} />
                Service Settings
              </h3>
              {selectedServices.length === 0 ? (
                <span className="text-sm text-gray-500 dark:text-gray-400">
                  Showing all services
                </span>
              ) : (
                <span className="text-sm text-blue-600 dark:text-blue-400">
                  Filtered to {selectedServices.length} service(s)
                </span>
              )}
            </div>
          </div>

          <div className="divide-y divide-gray-200 dark:divide-yorkhost-darkBorder">
            {services
              .filter(service => selectedServices.length === 0 || selectedServices.includes(service.id))
              .map((service) => (
              <motion.div
                key={service.id}
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="p-6"
              >
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-3 mb-4">
                      <h4 className="text-lg font-medium text-gray-900 dark:text-white">{service.name}</h4>
                      <div className="flex items-center gap-2">
                        <div className={clsx(
                          'w-3 h-3 rounded-full',
                          service.autoIncidentEnabled ? 'bg-green-500' : 'bg-gray-400'
                        )}></div>
                        <span className="text-sm text-gray-500 dark:text-gray-400">
                          {service.autoIncidentEnabled ? 'Enabled' : 'Disabled'}
                        </span>
                      </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-4">
                      {/* Enable/Disable Toggle */}
                      <div>
                        <label className="flex items-center gap-2">
                          <input
                            type="checkbox"
                            checked={service.autoIncidentEnabled}
                            onChange={(e) => updateServiceSettings(service.id, {
                              autoIncidentEnabled: e.target.checked
                            })}
                            className="rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                            disabled={saving === service.id}
                          />
                          <span className="text-sm font-medium text-gray-700 dark:text-gray-300">
                            Auto-incidents enabled
                          </span>
                        </label>
                      </div>

                      {/* Threshold Setting */}
                      <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                          Failure Threshold
                        </label>
                        <div className="flex items-center gap-2">
                          <input
                            type="number"
                            min="1"
                            max="10"
                            value={service.autoIncidentThreshold}
                            onChange={(e) => updateServiceSettings(service.id, {
                              autoIncidentThreshold: parseInt(e.target.value)
                            })}
                            className="w-20 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm dark:bg-gray-800 dark:text-white"
                            disabled={saving === service.id || !service.autoIncidentEnabled}
                          />
                          <span className="text-sm text-gray-500 dark:text-gray-400">failed checks</span>
                        </div>
                      </div>

                      {/* Cooldown Setting */}
                      <div>
                        <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1">
                          Cooldown Period
                        </label>
                        <div className="flex items-center gap-2">
                          <input
                            type="number"
                            min="60"
                            max="3600"
                            step="60"
                            value={service.autoIncidentCooldown}
                            onChange={(e) => updateServiceSettings(service.id, {
                              autoIncidentCooldown: parseInt(e.target.value)
                            })}
                            className="w-20 px-2 py-1 border border-gray-300 dark:border-gray-600 rounded text-sm dark:bg-gray-800 dark:text-white"
                            disabled={saving === service.id || !service.autoIncidentEnabled}
                          />
                          <span className="text-sm text-gray-500 dark:text-gray-400">seconds</span>
                        </div>
                      </div>
                    </div>

                    {/* Recent Auto-Incidents */}
                    {service.incidents.length > 0 && (
                      <div>
                        <h5 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                          Recent Auto-Incidents
                        </h5>
                        <div className="space-y-2">
                          {service.incidents.map((incident) => (
                            <div
                              key={incident.id}
                              className="flex items-center justify-between p-3 bg-gray-50 dark:bg-gray-800 rounded-lg"
                            >
                              <div className="flex items-center gap-3">
                                <span className={clsx(
                                  'px-2 py-1 text-xs font-medium rounded-full',
                                  getStatusColor(incident.status)
                                )}>
                                  {incident.status}
                                </span>
                                <span className="text-sm text-gray-900 dark:text-white">
                                  {incident.title}
                                </span>
                                {incident.manualTakeover && (
                                  <div className="flex items-center gap-1">
                                    <User size={12} className="text-blue-600" />
                                    <span className="text-xs text-blue-600">Manual Control</span>
                                  </div>
                                )}
                              </div>
                              <div className="flex items-center gap-2">
                                <span className="text-xs text-gray-500">
                                  {new Date(incident.startTime).toLocaleDateString()}
                                </span>
                                {incident.isAutoGenerated && !incident.manualTakeover && (
                                  <button
                                    onClick={() => takeControl(incident.id)}
                                    className="p-1 text-blue-600 hover:text-blue-700 transition-colors"
                                    title="Take manual control"
                                  >
                                    <UserCheck size={14} />
                                  </button>
                                )}
                                <button
                                  onClick={() => window.open(`/admin/incidents/${incident.id}`, '_blank')}
                                  className="p-1 text-gray-500 hover:text-gray-700 transition-colors"
                                  title="View incident"
                                >
                                  <Eye size={14} />
                                </button>
                              </div>
                            </div>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>

                  {saving === service.id && (
                    <div className="flex items-center gap-2 text-blue-600">
                      <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-blue-600"></div>
                      <span className="text-sm">Saving...</span>
                    </div>
                  )}
                </div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>
    </AdminLayout>
  )
}